---
  - name: "Install required apt packages"
    apt:
      package:
        - openvpn
        - easy-rsa
      update_cache: yes

  - name: "Add setup-team-openvpn.sh script"
    template:
      src: files/setup-team-openvpn.j2
      dest: /opt/setup-team-openvpn.sh
      mode: "755"

  - name: "Enable ipv4 forward"
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes

  - name: Configure team openvpn
    shell: /opt/setup-team-openvpn.sh