---
  - hosts: all
    become: yes
    become_method: sudo
    vars: 
      ansible_python_interpreter: /usr/bin/python3
    roles:
      - blackstab
    tasks:
      - name: Systemctl
        systemd:
          state: started
          name: blackStab


